# Generated by Django 5.1.6 on 2025-02-21 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rediomain', '0002_remove_answer_id_remove_question_id_answer_a_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rediomain.question'),
            preserve_default=False,
        ),
    ]
