# Generated by Django 5.1.6 on 2025-02-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rediomain', '0003_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='a_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='q_id',
            new_name='id',
        ),
    ]
