# Generated by Django 5.1.6 on 2025-02-24 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rediomain', '0005_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='question_id',
        ),
        migrations.AddField(
            model_name='upvote',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rediomain.answer'),
            preserve_default=False,
        ),
    ]
